use_frameworks!

platform :ios, '10.0'

target 'MultiCalendarKit_Example' do
  pod 'MultiCalendarKit', :path => '../'

  target 'MultiCalendarKit_Tests' do
  # RxSwift
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'RxGesture'
  pod 'RxDataSources', '~> 5.0'

  # SnapKit
  pod 'SnapKit', '~> 5.6.0'

  # Then
  pod 'Then'

    
  end
end
