use_frameworks!

platform :ios, '13.0'

target 'MultiCalendarKit_Example' do
  pod 'MultiCalendarKit', :path => '../'

  target 'MultiCalendarKit_Tests' do
  # RxSwift
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'RxGesture'
  pod 'RxDataSources', '~> 5.0'

  # SnapKit
  pod 'SnapKit', '~> 5.6.0'

  # Then
  pod 'Then'

    
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0' # 원하는 최소 버전
      end
    end
end